import os

from dotenv import load_dotenv


load_dotenv()


DATABASE_PATH = os.getenv("DATABASE_PATH")
QUERY_TOT_INIT=os.getenv("QUERY_TOT_INIT")
CREATE_TABLE_REPOSITORY_CHANGES_SUMMORY=os.getenv("CREATE_TABLE_REPOSITORY_CHANGES_SUMMORY")
INSERT_INTO_REPOSITORY_CHANGES_SUMMORY=os.getenv("INSERT_INTO_REPOSITORY_CHANGES_SUMMORY")
GET_ALL_REPOSITORY_CHANGES_SUMMORY=os.getenv("GET_ALL_REPOSITORY_CHANGES_SUMMORY")
UPDATE_REPOSITORY_CHANGES_SUMMORY=os.getenv("UPDATE_REPOSITORY_CHANGES_SUMMORY")
GET_ALL_REPOSITORY_CHANGES_SUMMORY_CONDITION=os.getenv("GET_ALL_REPOSITORY_CHANGES_SUMMORY_CONDITION")
DIR_CHARTS=os.getenv("DIR_CHARTS")
GET_CHANGES_FROM_NAME=os.getenv("GET_CHANGES_FROM_NAME")
GET_ALL_REPOSITORY=os.getenv("GET_ALL_REPOSITORY")
CREATE_TABLE_SELECTOR_SUMMARY=os.getenv("CREATE_TABLE_SELECTOR_SUMMARY")
INSERT_INTO_SELECTOR_SUMMORY=os.getenv("INSERT_INTO_SELECTOR_SUMMORY")
CHECH_EXISTS_ROWS_SELECTOR_SUMMARTY=os.getenv("CHECH_EXISTS_ROWS_SELECTOR_SUMMARTY")
SUM_REPOSITPORY_SUMMARY=os.getenv("SUM_REPOSITPORY_SUMMARY")
QUERY_SUM_REPOSITORY_CHANGES_SUMMERY=os.getenv("QUERY_SUM_REPOSITORY_CHANGES_SUMMERY")