import os
from dotenv import load_dotenv


load_dotenv()


DATABASE_PATH = os.getenv("DATABASE_PATH")
QUERY_GET_ALL_TESTING = os.getenv("QUERY_GET_ALL_TESTING")
CSV_OUTPUT_DIR=os.getenv("CSV_OUTPUT_DIR")
GIT_REPO_DIR=os.getenv("GIT_REPO_DIR")
DB_REPORT_PATH=os.getenv("DB_REPORT_PATH")
CREATE_TABLE_CHANGES=os.getenv("CREATE_TABLE_CHANGES")
INSERT_INTO_CHANGES=os.getenv("INSERT_INTO_CHANGES")

CREATE_TABLE_REPO=os.getenv("CREATE_TABLE_REPO")
INSERT_INTO_REPO=os.getenv("INSERT_INTO_REPO")
QUERY_FIND_REPOSITORY_BY_NAME=os.getenv("QUERY_FIND_REPOSITORY_BY_NAME")
QUERY_UPDATE_REPOSITORY_TOTAL_COMMIT=os.getenv("QUERY_UPDATE_REPOSITORY_TOTAL_COMMIT")